### ISSUE TITLE
Low fidlelity design(s)

### ISSUE THREAD

**Issue by ninmore** [VirtualEdge/VirtualEdgeProject#2]
To finish low fidelity designs. Remember to put the designs in the mockups folder. @caleb100993 @Sahrash @Deuvient

**Comment by ninmore** [comment]
@caleb100993 @Sahrash

**Comment by Deuvient** [comment]
Just to let you know, we did do them in class but remember Bekki took them to do the medium and I believe that Caleb has done some better ones, so this task has been met, just requires an upload.

**Comment by bekkimorgans** [comment]
Yeah I've got the low ones, they need to be re-done though and caleb sent me two, one of the scan page and one of the like when you click scan page.

**Comment by caleb100993** [comment]
yeah ive done 2 better pages of designs but i cant get the colour scheme
codes we got from the website cos i cant find the website. you wouldnt mind
taking a pic of them and sending it to me please bekki?

**Comment by Deuvient** [comment]
#588b21
#273d0e
Those are the two greens

**Comment by caleb100993** [comment]
cheers martin!
