### ISSUE TITLE
Medium fidelity designs

### ISSUE THREAD

**Issue by ninmore** [VirtualEdge/VirtualEdgeProject#3]
Complete the medium fidelity designs and put them in the mockups folder. @bekkimorgans

**Comment by bekkimorgans** [comment]
![exhibit page](https://cloud.githubusercontent.com/assets/10152606/5888742/667d9292-a403-11e4-91fa-216a16d06bb3.png)

**Comment by ninmore** [comment]
@bekkimorgans Thats fine for the medium fidelity. I think that the search could be different apart from round edges but thats fine. You may be able to change some stuff one low fidelity has been uploaded.

**Comment by bekkimorgans** [comment]
Yeah I just realised the button says scan and it should say view 3D whatever so I'll sort that now. Yeah I'll make changes when they're but moqups didn't really allow for much else so might have to just be changed in high fidelity. I emailed you, didn't realise you'd be on.

**Comment by ninmore** [comment]
Okay thats fine. I am always on haha. @bekkimorgans

**Comment by bekkimorgans** [comment]
![exhibit page](https://cloud.githubusercontent.com/assets/10152606/5888855/42cd9dc6-a406-11e4-90b9-174e0d9fd0a0.png)

**Comment by ninmore** [comment]
That's great. You can add more if you want also don't forget about material design <a href="http://www.google.com/design/">LINK</a>

**Comment by bekkimorgans** [comment]
Yeah, I'm just doing more now, they're just like basics for now based on the low fidelity I've been given but will change them when proper low ones are added, just so you and Martin have ideas for the high ones.

**Comment by ninmore** [comment]
On 24/01/2015 20:25, bekkimorgans wrote:
>
> Yeah, I'm just doing more now, they're just like basics for now based 
> on the low fidelity I've been given but will change them when proper 
> low ones are added, just so you and Martin have ideas for the high ones.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/VirtualEdge/VirtualEdgeProject/issues/3#issuecomment-71335698>.
>
  Ok thats fine.

**Comment by bekkimorgans** [comment]
HELP KYLE! How do I add the pictures into the mockups folder?

**Comment by ninmore** [comment]
Look in the google drive folder there is a tutorial I made.

**Comment by bekkimorgans** [comment]
Erm I still don't get how to upload them, google says to upload it to the repository and push it in/up/whatever but I don't get it

**Comment by ninmore** [comment]
On 24/01/2015 23:56, bekkimorgans wrote:
>
> Erm I still don't get how to upload them, google says to upload it to 
> the repository and push it in/up/whatever but I don't get it
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/VirtualEdge/VirtualEdgeProject/issues/3#issuecomment-71343649>.
>
Just put the files in the mockups folder and on the github application 
look for sync button or a submit commit tab.
