### ISSUE TITLE
Have a working prototype

### ISSUE THREAD

**Issue by ninmore** [VirtualEdge/VirtualEdgeProject#5]
We need to have a finished project by the milestone. @VirtualEdge/owners

**Comment by caleb100993** [comment]
What's the name of that website we were using for the Google layouts and
what not?

**Comment by ninmore** [comment]
On 23/01/2015 18:50, caleb100993 wrote:
> What's the name of that website we were using for the Google layouts and
> what not?
> On 23 Jan 2015 15:23, "Kyle Naude" <notifications@github.com> wrote:
>
> > We need to have a finished project by the milestone. 
> @VirtualEdge/owners
> > <https://github.com/orgs/VirtualEdge/teams/owners>
> >
> > â€”
> > Reply to this email directly or view it on GitHub
> > <https://github.com/VirtualEdge/VirtualEdgeProject/issues/5>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/VirtualEdge/VirtualEdgeProject/issues/5#issuecomment-71243717>.
>
Material design.
