### ISSUE TITLE
Layout flow?

### ISSUE THREAD

**Issue by ninmore** [VirtualEdge/VirtualEdgeProject#6]
While you are also doing the designs I need a flow diagram or a just a diagram to show how the user show use the program for example:
![ic533766](https://cloud.githubusercontent.com/assets/1499355/5894120/53010748-a4f4-11e4-9298-2c43d24b7d2d.png)

**Comment by ninmore** [comment]
@VirtualEdge/owners Cheers

**Comment by ninmore** [comment]
Fixed and Answered.

**Comment by bekkimorgans** [comment]
Has this been uploaded anywhere?
